routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
@require('assets.php');

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/formshareholder', 'ShareHolderController@index')->name('/admin/formshareholder');


Route::group(['prefix' =>ROOT_DIR.'admin', 'middleware' => ['auth'], 'as' => 'admin.'], function () {

    //user register and edit routes
    Route::get('/user', ['uses'=>'UserController@index','as'=>'list_user']);

    Route::get('/user/register',['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit
    Route::get('/user/edit/{id}', ['uses'=>'UserController@editUser','as'=>'edit_user']);
    Route::post('/user/edit', ['uses'=>'UserController@post_editUser','as'=>'update_user']);

    //delete user
    Route::post('/user/delete', ['uses'=>'UserController@deleteUser','as'=>'delete_user']);

    //list user group permission
    Route::get('/permission/group', ['uses'=>'PermissionController@index','as'=>'list_group']);
    Route::get('/permission/group/create', ['uses'=>'PermissionController@showGroupForm','as'=>'register_group']);
    Route::post('/permission/store', ['uses'=>'PermissionController@postGroupForm','as'=>'store_group']);
    Route::get('/permission/view/{id}', ['uses'=>'PermissionController@viewGroup','as'=>'view_group']);

//    Route::get('/permission/group/edit', ['uses'=>'PermissionController@showGroupForm','as'=>'list_group']);


});

//profile routes
Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => ['auth'], 'as' => 'profile.'], function () {

    //user  profile register and edit routes
    Route::get('/{key}',['uses'=>'Usercontroller@getProfile','as'=>'list_profile']);
    Route::post('/edit/profile', ['uses'=>'UserController@editProfile','as'=>'edit']);


});


Route::group(['prefix' =>ROOT_DIR.'shareholder', 'middleware' => ['auth','can:shareholder'], 'as' => 'shareholder.'], function () {

    //share group route
    Route::get('/group', ['uses'=>'ShareHolder\ShareGroupController@index','as'=>'list_group']);
    Route::get('/group/edit/{id}', ['uses'=>'ShareHolder\ShareGroupController@editGroup','as'=>'edit_group']);
    Route::post('/group/add', ['uses'=>'ShareHolder\ShareGroupController@addGroup','as'=>'add_group']);
    Route::post('/group/delete', ['uses'=>'ShareHolder\ShareGroupController@deleteGroup','as'=>'delete_group']);


    //share form
    Route::get('/add_form', ['uses'=>'ShareHolder\ShareHolderController@index','as'=>'add_form']);
    Route::post('/process_form', ['uses'=>'ShareHolder\ShareHolderController@process','as'=>'process_form']);
    Route::get('/list_form', ['uses'=>'ShareHolder\ShareHolderController@list','as'=>'list_form']);
    Route::get('/view/{id}', ['uses'=>'ShareHolder\ShareHolderController@view','as'=>'view']);

    // Edit Form Share and Installment Details

        //Edit Menu
            Route::get('/edit/{id}', ['uses'=>'ShareHolder\ShareHolderController@editMenu','as'=>'edit']);

            Route::get('/edit/form/{id}', ['uses'=>'ShareHolder\ShareHolderController@editForm','as'=>'edit_form']);
            Route::post('/edit/form', ['uses'=>'ShareHolder\ShareHolderController@posteditForm','as'=>'update_form']);

            Route::get('/edit_document/{id}', ['uses'=>'ShareHolder\ShareHolderController@edit_document','as'=>'edit_document']);
            Route::post('/edit_document_form}', ['uses'=>'ShareHolder\ShareHolderController@edit_document_form','as'=>'edit_document_form']);

            Route::get('/edit_installment/{id}', ['uses'=>'ShareHolder\InstallmentController@getInstallmentInformation','as'=>'edit_installment']);
            Route::post('/edit_installment_form/{id}', ['uses'=>'ShareHolder\InstallmentController@editInstallmentInformation','as'=>'edit_installment_form']);


    //end_edit

    //installment
    Route::get('/installment', ['uses'=>'ShareHolder\InstallmentController@index','as'=>'installment']);
    Route::get('/add_installment/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@add_installment','as'=>'add_installment']);
    Route::post('/process_installment', ['uses'=>'ShareHolder\InstallmentController@process_installment','as'=>'process_installment']);

    Route::get('/installment/all/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@view_installment','as'=>'view_installment']);

    Route::get('/installment/detail/{id}', ['uses'=>'ShareHolder\InstallmentController@getSingleInstallment','as'=>'getSingleInstallment']);



    //Notification Routes
    Route::get('/notification', ['uses'=>'ShareHolder\NotificationController@index','as'=>'notification']);
    Route::get('/notiication/message/{id}', ['uses'=>'ShareHolder\NotificationController@showMessageForm','as'=>'notification_message']);
    Route::post('/notiication/message', ['uses'=>'ShareHolder\NotificationController@post_message','as'=>'post_message']);


});


/*Route::group(['prefix' =>ROOT_DIR.'assetsmanagement', 'middleware' => ['auth','can:ams'], 'as' => 'asset.'], function () {*/

    //share group route
    /*Route::get('/add_asset', ['uses'=>'AssetsManagement\ProductController@addAsset','as'=>'add_asset']);*/
    /*Route::post('/add_asset', ['uses'=>'AssetsManagement\ProductController@assetForm','as'=>'add_asset']);
    Route::get('/list_asset', ['uses'=>'AssetsManagement\ProductController@assetList','as'=>'list_asset']);*/
    /*Route::get('/edit_asset/{id}', ['uses'=>'AssetsManagement\ProductController@editAsset','as'=>'edit_asset']);*/
    /*Route::post('/update_asset', ['uses'=>'AssetsManagement\ProductController@updateAsset','as'=>'update_asset']);*/
    /*Route::post('/delete_asset', ['uses'=>'AssetsManagement\ProductController@deleteAsset','as'=>'delete_asset']);*/
    /*Route::get('/view_asset/{id}', ['uses'=>'AssetsManagement\ProductController@viewAsset','as'=>'view_asset']);*/

    /*Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);*/
    /*Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);*/

   /* Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);*/
   


   /* Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);

    Route::get('purchase_form', ['uses'=>'AssetsManagement\ProductController@purchaseForm','as'=>'purchase_form']);
    Route::post('purchase_form', ['uses'=>'AssetsManagement\RequisitionFormController@addPurchaseForm','as'=>'purchase_form']);*/


/*});*/

Route::group(['prefix' =>ROOT_DIR.'storekeeper',  'as' => 'store.'], function () {

    //Storekeeper group route

    //add product directly by the store.
    Route::get('/product/add', ['uses'=>'AssetsManagement\ProductController@addProduct','as'=>'add_product']);
    Route::post('/add_product', ['uses'=>'AssetsManagement\ProductController@productForm','as'=>'store_product']);
    Route::get('/list_product', ['uses'=>'AssetsManagement\ProductController@productList','as'=>'list_product']);
    Route::get('/edit_product/{id}', ['uses'=>'AssetsManagement\ProductController@editProduct','as'=>'edit_product']);
    Route::post('/update_product', ['uses'=>'AssetsManagement\ProductController@updateProduct','as'=>'update_product']);
    Route::post('/delete_product', ['uses'=>'AssetsManagement\ProductController@deleteProduct','as'=>'delete_product']);
    Route::get('/view_product/{id}', ['uses'=>'AssetsManagement\ProductController@viewProduct','as'=>'view_product']);

    //end add product route

    // product add after purchase form
    Route::get('/product/purchase/add/{id}', ['uses'=>'AssetsManagement\ProductController@addProductAfterPurchaseForm','as'=>'add_purchase_product']);
    Route::post('/product/purchase/add', ['uses'=>'AssetsManagement\ProductController@storeProductAfterPurchaseForm','as'=>'store_purchase_product']);

    // end product add after purchase form

    //add vendor
    Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);
    Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);

    Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);
    Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);
    //end vendor route

    //Product Category list and update

resources/views/home.blade.php
@extends('layouts.app')

@section('page_title')
    Dashboard
@endsection

@section('page-title')
    Dashboard || {{$module}}
@endsection
@section('content')
    {{--superadmin--}}
    @if($usertype == 0)
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat blue-madison">
                <div class="visual">
                    <i class="fa fa-comments"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{$total_user}}
                    </div>

                    <div class="desc">
                        Total Users
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat red-intense">
                <div class="visual">
                    <i class="fa fa-bar-chart-o"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{$user_shareholder}}

                    </div>
                    <div class="desc">
                            Share Holder User
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat green-haze">
                <div class="visual">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{$user_assets}}
                    </div>
                    <div class="desc">
                            Assets Management User
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat purple-plum">
                <div class="visual">
                    <i class="fa fa-globe"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{$user_dms}}
                    </div>
                    <div class="desc">
                            Document Management User
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Share Holder --}}
    @elseif($usertype == 1)
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_shareholder}}
                        </div>

                        <div class="desc">
                            Users
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat green-haze">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$share_group}}
                        </div>
                        <div class="desc">
                            Share Group
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat red-intense">
                    <div class="visual">
                        <i class="fa fa-bar-chart-o"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$share_form}}

                        </div>
                        <div class="desc">
                                Total Share Form
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat purple-plum">
                    <div class="visual">
                        <i class="fa fa-globe"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$completed_installment}}
                        </div>
                        <div class="desc">
                            Completed Installment
                        </div>
                    </div>

                </div>
            </div>
        </div>

    {{-- Assets Management--}}
    @elseif($usertype == 2)
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$total_user}}
                        </div>

                        <div class="desc">
                            Total Users
                        </div>
                    </div>
                    <a class="more" href="{{route('admin.list_user')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat red-intense">
                    <div class="visual">
                        <i class="fa fa-bar-chart-o"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_shareholder}}

                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Share Holder User
                            @else
                                Total Share Form
                            @endif
                        </div>
                    </div>
                    <a class="more" href="{{route('shareholder.list_form')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat green-haze">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_assets}}
                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Assets Management User
                            @else
                                Total Share Group
                            @endif

                        </div>
                    </div>
                    <a class="more" href="{{route('shareholder.list_group')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat purple-plum">
                    <div class="visual">
                        <i class="fa fa-globe"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_dms}}
                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Document Management User
                            @else
                                Total Completed Installment
                            @endif

                        </div>
                    </div>
                    <a class="more" href="javascript:;">
                        {{--<i class="m-icon-swapright m-icon-white"></i>--}}
                    </a>
                </div>
            </div>
        </div>

    {{-- DMS--}}
    @else
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$total_user}}
                        </div>

                        <div class="desc">
                            Total Users
                        </div>
                    </div>
                    <a class="more" href="{{route('admin.list_user')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat red-intense">
                    <div class="visual">
                        <i class="fa fa-bar-chart-o"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_shareholder}}

                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Share Holder User
                            @else
                                Total Share Form
                            @endif
                        </div>
                    </div>
                    <a class="more" href="{{route('shareholder.list_form')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat green-haze">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_assets}}
                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Assets Management User
                            @else
                                Total Share Group
                            @endif

                        </div>
                    </div>
                    <a class="more" href="{{route('shareholder.list_group')}}">
                        View more <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat purple-plum">
                    <div class="visual">
                        <i class="fa fa-globe"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            {{$user_dms}}
                        </div>
                        <div class="desc">
                            @if($usertype == 0)
                                Document Management User
                            @else
                                Total Completed Installment
                            @endif

                        </div>
                    </div>
                    <a class="more" href="javascript:;">
                        {{--<i class="m-icon-swapright m-icon-white"></i>--}}
                    </a>
                </div>
            </div>
        </div>
    @endif
@endsection