routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
@require('assets.php');

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/formshareholder', 'ShareHolderController@index')->name('/admin/formshareholder');


Route::group(['prefix' =>ROOT_DIR.'admin', 'middleware' => ['auth'], 'as' => 'admin.'], function () {

    //user register and edit routes
    Route::get('/user', ['uses'=>'UserController@index','as'=>'list_user']);

    Route::get('/user/register',['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit
    Route::get('/user/edit/{id}', ['uses'=>'UserController@editUser','as'=>'edit_user']);
    Route::post('/user/edit', ['uses'=>'UserController@post_editUser','as'=>'update_user']);

    //delete user
    Route::post('/user/delete', ['uses'=>'UserController@deleteUser','as'=>'delete_user']);

    //list user group permission
    Route::get('/permission/group', ['uses'=>'PermissionController@index','as'=>'list_group']);
    Route::get('/permission/group/create', ['uses'=>'PermissionController@showGroupForm','as'=>'register_group']);
    Route::post('/permission/store', ['uses'=>'PermissionController@postGroupForm','as'=>'store_group']);
    Route::get('/permission/view/{id}', ['uses'=>'PermissionController@viewGroup','as'=>'view_group']);

//    Route::get('/permission/group/edit', ['uses'=>'PermissionController@showGroupForm','as'=>'list_group']);


});

//profile routes
Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => ['auth'], 'as' => 'profile.'], function () {

    //user  profile register and edit routes
    Route::get('/{key}',['uses'=>'Usercontroller@getProfile','as'=>'list_profile']);
    Route::post('/edit/profile', ['uses'=>'UserController@editProfile','as'=>'edit']);


});


Route::group(['prefix' =>ROOT_DIR.'shareholder', 'middleware' => ['auth','can:shareholder'], 'as' => 'shareholder.'], function () {

    //share group route
    Route::get('/group', ['uses'=>'ShareHolder\ShareGroupController@index','as'=>'list_group']);
    Route::get('/group/edit/{id}', ['uses'=>'ShareHolder\ShareGroupController@editGroup','as'=>'edit_group']);
    Route::post('/group/add', ['uses'=>'ShareHolder\ShareGroupController@addGroup','as'=>'add_group']);
    Route::post('/group/delete', ['uses'=>'ShareHolder\ShareGroupController@deleteGroup','as'=>'delete_group']);


    //share form
    Route::get('/add_form', ['uses'=>'ShareHolder\ShareHolderController@index','as'=>'add_form']);
    Route::post('/process_form', ['uses'=>'ShareHolder\ShareHolderController@process','as'=>'process_form']);
    Route::get('/list_form', ['uses'=>'ShareHolder\ShareHolderController@list','as'=>'list_form']);
    Route::get('/view/{id}', ['uses'=>'ShareHolder\ShareHolderController@view','as'=>'view']);

    // Edit Form Share and Installment Details

        //Edit Menu
            Route::get('/edit/{id}', ['uses'=>'ShareHolder\ShareHolderController@editMenu','as'=>'edit']);

            Route::get('/edit/form/{id}', ['uses'=>'ShareHolder\ShareHolderController@editForm','as'=>'edit_form']);
            Route::post('/edit/form', ['uses'=>'ShareHolder\ShareHolderController@posteditForm','as'=>'update_form']);

            Route::get('/edit_document/{id}', ['uses'=>'ShareHolder\ShareHolderController@edit_document','as'=>'edit_document']);
            Route::post('/edit_document_form}', ['uses'=>'ShareHolder\ShareHolderController@edit_document_form','as'=>'edit_document_form']);

            Route::get('/edit_installment/{id}', ['uses'=>'ShareHolder\InstallmentController@getInstallmentInformation','as'=>'edit_installment']);
            Route::post('/edit_installment_form/{id}', ['uses'=>'ShareHolder\InstallmentController@editInstallmentInformation','as'=>'edit_installment_form']);


    //end_edit

    //installment
    Route::get('/installment', ['uses'=>'ShareHolder\InstallmentController@index','as'=>'installment']);
    Route::get('/add_installment/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@add_installment','as'=>'add_installment']);
    Route::post('/process_installment', ['uses'=>'ShareHolder\InstallmentController@process_installment','as'=>'process_installment']);

    Route::get('/installment/all/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@view_installment','as'=>'view_installment']);

    Route::get('/installment/detail/{id}', ['uses'=>'ShareHolder\InstallmentController@getSingleInstallment','as'=>'getSingleInstallment']);



    //Notification Routes
    Route::get('/notification', ['uses'=>'ShareHolder\NotificationController@index','as'=>'notification']);
    Route::get('/notiication/message/{id}', ['uses'=>'ShareHolder\NotificationController@showMessageForm','as'=>'notification_message']);
    Route::post('/notiication/message', ['uses'=>'ShareHolder\NotificationController@post_message','as'=>'post_message']);


});


/*Route::group(['prefix' =>ROOT_DIR.'assetsmanagement', 'middleware' => ['auth','can:ams'], 'as' => 'asset.'], function () {*/

    //share group route
    /*Route::get('/add_asset', ['uses'=>'AssetsManagement\ProductController@addAsset','as'=>'add_asset']);*/
    /*Route::post('/add_asset', ['uses'=>'AssetsManagement\ProductController@assetForm','as'=>'add_asset']);
    Route::get('/list_asset', ['uses'=>'AssetsManagement\ProductController@assetList','as'=>'list_asset']);*/
    /*Route::get('/edit_asset/{id}', ['uses'=>'AssetsManagement\ProductController@editAsset','as'=>'edit_asset']);*/
    /*Route::post('/update_asset', ['uses'=>'AssetsManagement\ProductController@updateAsset','as'=>'update_asset']);*/
    /*Route::post('/delete_asset', ['uses'=>'AssetsManagement\ProductController@deleteAsset','as'=>'delete_asset']);*/
    /*Route::get('/view_asset/{id}', ['uses'=>'AssetsManagement\ProductController@viewAsset','as'=>'view_asset']);*/

    /*Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);*/
    /*Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);*/

   /* Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);*/
   


   /* Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);

    Route::get('purchase_form', ['uses'=>'AssetsManagement\ProductController@purchaseForm','as'=>'purchase_form']);
    Route::post('purchase_form', ['uses'=>'AssetsManagement\RequisitionFormController@addPurchaseForm','as'=>'purchase_form']);*/


/*});*/

Route::group(['prefix' =>ROOT_DIR.'storekeeper',  'as' => 'store.'], function () {

    //Storekeeper group route

    //add product directly by the store.
    Route::get('/product/add', ['uses'=>'AssetsManagement\ProductController@addProduct','as'=>'add_product']);
    Route::post('/add_product', ['uses'=>'AssetsManagement\ProductController@productForm','as'=>'store_product']);
    Route::get('/list_product', ['uses'=>'AssetsManagement\ProductController@productList','as'=>'list_product']);
    Route::get('/edit_product/{id}', ['uses'=>'AssetsManagement\ProductController@editProduct','as'=>'edit_product']);
    Route::post('/update_product', ['uses'=>'AssetsManagement\ProductController@updateProduct','as'=>'update_product']);
    Route::post('/delete_product', ['uses'=>'AssetsManagement\ProductController@deleteProduct','as'=>'delete_product']);
    Route::get('/view_product/{id}', ['uses'=>'AssetsManagement\ProductController@viewProduct','as'=>'view_product']);

    //end add product route

    // product add after purchase form
    Route::get('/product/purchase/add/{id}', ['uses'=>'AssetsManagement\ProductController@addProductAfterPurchaseForm','as'=>'add_purchase_product']);
    Route::post('/product/purchase/add', ['uses'=>'AssetsManagement\ProductController@storeProductAfterPurchaseForm','as'=>'store_purchase_product']);

    // end product add after purchase form

    //add vendor
    Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);
    Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);

    Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);
    Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);
    //end vendor route

    //Product Category list and update

app/ShareGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ShareGroup extends Model
{
    protected  $table = 'share_group';
    public $timestamps = false;

    protected $fillable = ['id'];



}

app/Http/Controllers/ShareHolder/NotificationController.php
<?php

namespace App\Http\Controllers\ShareHolder;

use App\FormShare;
use App\Helper\Tools;
use App\InstallmentInformation;
use App\Payment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Mail\NotificationPayment;
use Symfony\Component\Console\Helper\Helper;

class NotificationController extends Controller
{
    public function index()
    {
        $payment_info = FormShare::with('payment_information')->get(['form_status','id','notification','proceeded_for']);
//        dd($payment_info);
//        $data = array();

        //initializing count for badge
        $count = 0;

        foreach ($payment_info as $value){
            $total_installment = $value->payment_information->no_of_installment;
            $temp = $value->proceeded_for . '_expiry_date';

            for($i = 1; $i <= $total_installment; $i ++) {

                if ($value->notification == 1) {

                    if ($value->form_status == $i) {
                        $payment = InstallmentInformation::where('share_form_id', $value->id)->first();
                        //                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->first_expiry_date)));
                        $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->$temp)));

                        if (date('Y-m-d') >= $days_ago) {
                            $count = $count + 1;

                            $data['form'] [] = FormShare::where('id', $value->id)->with('payment_information')->first();

                        }
                    }
                }
            }

//            if($value->notification == 1){
//                $check[] = $count;
//                echo $count;
//
//                if($value->form_status == $count){
//                    $payment = InstallmentInformation::where('share_form_id',$value->id)->first();
////                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->first_expiry_date)));
//                    $temp = $value->proceeded_for.'_expiry_date';
//                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->$temp)));
//
//                    if(date('Y-m-d') >= $days_ago){
//
//                        $data['form'] [] = FormShare::where('id',$value->id)->with('payment_information')->first();
//
//                    }
//                }
//                /*else if($value->form_status == 2){
//
//                    $payment = InstallmentInformation::where('share_form_id',$value->id)->first();
//                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->second_expiry_date)));
//
//
//                    if(date('Y-m-d') >= $days_ago){
//                        $data['form'] [] = FormShare::where('id',$value->id)->with('payment_information')->first();
//
//                    }
//                }*/
//            }

        }



        if(!isset($data)){
            $data['token'] = 0;
        }
        else{
            $data['token'] = 1;

        }

        return view('shareholder.Notification.index',$data);

    }

    public function showMessageForm($id){
        $data['installment'] = FormShare::where('id',$id)->with('payment_information')->first();

        $form_status= $data['installment']->form_status;
        $data['installment_detail'] = Tools::getInstallmentDetail($id,$form_status);

        $expiry_date = new \DateTime($data['installment_detail']->expiry_date);
        $current_date = new \DateTime();
        $interval = $expiry_date->diff($current_date);
        if($expiry_date > $current_date){
            $data['remaining_days']= $interval->days + 1;
        }
        else{
            $data['overdue_days']= $interval->days ;

        }
//        dd($data);

        return view('shareholder.Notification.form_message',$data);
    }

    public function post_message(Request $request){
        $this->validate($request,[
            'message' => 'required|min:10',
            'user_email' => 'required|email'
        ]);
        $data = $request->all();

        //call mailable class and send mail.
        \Mail::to($request->user_email)->send(new NotificationPayment($data));

        //after that update form_share table notification columnt to 0
        $id = $request->id;

        $form = FormShare::find($id);

        //updating notification to 0 to not show it again
        $form->notification = 0;
        $form->save();

        \Session::flash('success','Notification Sent Successfully');
        return redirect()->route('shareholder.notification');
    }
}

app/Http/Controllers/ShareHolder/ShareGroupController.php
<?php

namespace App\Http\Controllers\ShareHolder;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ShareGroup;
use App\Helper\Tools;
use Illuminate\Support\Facades\Validator;
use Session;

class ShareGroupController extends Controller
{
    public function index(){

        $data['group'] = ShareGroup::orderBy('id','DESC')->where('slug',1)->get();
        return view('shareholder.ShareGroup.list_group',$data);
    }

    public function editGroup($id){
        $data['group'] = ShareGroup::find($id);

        if(empty($data['group'])) {
            abort(404);
        }

        return view('shareholder.ShareGroup.edit_group',$data);
    }

    public function addGroup(Request $request){

        $this->validate($request,[
            'group_name' => 'required',
            'action' => 'required'
        ]);
//        dd($request->all());

        //slug 1 = group
        //slug 2 = individual

        if($request->action == 'add'){
            $group = new ShareGroup();
            $group->slug = 1;
            $group->created_at = date('Y-m-d h:i:s');
            $group->created_by = \Auth::user()->id;
        }
        else
        {
            $group =  ShareGroup::find($request->id);
        }


        $group->name = $request->group_name;

        $group->save();

        if($request->action == 'add'){
            \Session::flash('success','Group Created Successfully');
            return redirect()->back();

        }
        else{
            \Session::flash('success','Group Updated Successfully');
            return redirect()->route('shareholder.list_group');

        }
    }

    public function deleteGroup(Request $request){
        $validator = Validator::make($request->all(), [
            'id' => 'required',
        ]);

        if ($validator->fails()) {
            \Session::flash('error','Error in Deleting Group');
            $responseData = Tools::setResponse('fail', 'Missing Parameter', '', '');
            $status = 422;

            return response()->json($responseData,$status);
        }

        $data = ShareGroup::find($request->id);
        $data->delete();

        \Session::flash('success','Group Deleted Successfully');
        return redirect()->back();
    }
}

resources/views/shareholder/ShareGroup/edit_group.blade.php
@extends('layouts.app')
@section('css')
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/select2/select2.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}" rel="stylesheet" type="text/css"/>
@endsection('css')

@section('page_title')
    Edit Share Group
@endsection('page-title')

@section('page-title')
    Edit Group
@endsection('page-title')

@section('content')

    <div class="col-md-4">
        <a href="{{route('shareholder.list_group')}}" class="btn btn-sm  btn-primary"><i class="fa fa-arrow-circle-left"></i> Back</a>
        <hr>
        <div class=" portlet light bordered" >
            <div class="row">
                <form role="form" action="{{ route('shareholder.add_group') }}" method="post">
                    @csrf
                    <div class="form-body">
                        <div class="form-group has-error">
                            <label>Group Name:</label>
                            <input type="text" name="group_name" class="form-control" placeholder="Enter Group Name" value="{{ $group->name ?? '' }}">

                            @if($errors->has('group_name'))
                                <span class="help-block ">
                                    * {{$errors->first('group_name')}}
                                </span>
                            @endif
                        </div>

                    </div>

                    <div class="form-actions right">
                        <input type="hidden" value="{{$group->id}}" name="id">
                        <input type="hidden" value="edit" name="action">
                        <button type="submit" class="btn green">
                            <i class="fa fa-plus-circle"></i> Update
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>




@endsection('content')
@section('scripts')

    {{--    <script src="{{ asset(STATIC_DIR.'assets/global/plugins/select2/select2.min.js') }}" type="text/javascript"></script>--}}
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}" type="text/javascript"></script>

    <script>
        jQuery(document).ready(function() {
            $('#group').DataTable();
        });
    </script>

@endsection('scripts')

resources/views/shareholder/ShareGroup/list_group.blade.php
@extends('layouts.app')

@section('css')
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/select2/select2.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}" rel="stylesheet" type="text/css"/>
@endsection('css')

@section('page_title')
    Share Group
@endsection('page-title')

@section('page-title')
    Group Listing
@endsection('page-title')

@section('content')

    <div class="col-md-8">
        <div class=" portlet light bordered" >
            <div class="row">
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-bordered dataTable no-footer" id="group" role="grid" aria-describedby="sample_editable_1_info">
                        <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" aria-sort="ascending" style="width: 211px;">
                                S.N.
                            </th>

                            <th class="sorting_asc" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" aria-sort="ascending" style="width: 211px;">
                                Group  Name
                            </th>

                            <th class="sorting_asc" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" aria-sort="ascending" style="width: 211px;">
                                Created At
                            </th>

                            <th class="sorting_asc" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" aria-sort="ascending" style="width: 211px;">
                                Action
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($group as $value)
                            <tr role="row" class="odd">
                                <td class="sorting_1">
                                    {{$loop->iteration}}
                                </td>

                                <td>
                                    {{$value->name}}
                                </td>

                                <td>
                                    {{$value->created_at}}
                                </td>

                                <td class="center">
                                    <a href="{{route('shareholder.edit_group',$value->id)}}" class="btn btn-sm btn-success">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>

                                    <a href="#deleteGroup" class="btn btn-sm red" data-ids="{{ $value->id }}" data-toggle="modal" data-rel="delete" data-user="{{$value->name}}">
                                    <i class="icon-trash"></i> Delete
                                    </a>
                                    {{--<button class="btn default btn-xs green-stripe"> <i class="fa fa-edit"></i> Edit</button>--}}
                                    {{--<button class="btn default btn-xs red-stripe"> <i class="icon-trash"></i> Delete</button>--}}


                                </td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class=" portlet light bordered" >
            <div class="row">
                <form role="form" action="{{ route('shareholder.add_group') }}" method="post">
                    @csrf
                    <div class="form-body">
                        <div class="form-group has-error">
                            <label>Group Name:</label>
                            <input type="text" name="group_name" class="form-control" placeholder="Enter Group Name">

                            @if($errors->has('group_name'))
                                <span class="help-block ">
                                    * {{$errors->first('group_name')}}
                                </span>
                            @endif
                        </div>

                    </div>

                    <div class="form-actions right">
                        <input type="hidden" value="add" name="action">
                        <button type="submit" class="btn green">
                            <i class="icon-plus"></i> Add
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    {{--modal start here.--}}
    <div id="showMessage" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content" style="margin-top: 200px;">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Group Deleted
                    </h4>
                </div>

                <div class="modal-body">
                    <i class="fa fa-check"></i> &nbsp; Group Deleted Successfully .
                </div>
                <input type="hidden" id="hidden_id">
                <div class="modal-footer" style="text-align: center;">
                    <button type="button" class="btn btn-danger green confirm_yes" id="show_message"><i class="icon-check"></i> Ok
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    </div>

    <div id="deleteGroup" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Delete Permanently
                    </h4>
                </div>
                <div class="modal-body"> Do you want to delete <span class='hidden_title'>" "</span>?</div>
                <input type="hidden" id="hidden_id">
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
                    </button>
                    <button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
                        No
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    </div>




@endsection('content')
@section('scripts')
    <script src="{{ asset(STATIC_DIR.'assets/global/plugins/select2/select2.min.js') }}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function() {
            $('#group').DataTable();
        });



        $('#deleteGroup').on('show.bs.modal', function (e) {
            //e.preventDefault();
            var button = $(e.relatedTarget);
            var ids = button.data('ids');
            var user = button.data('user');

            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modalfooter #confirm').data('form', form);
            $("#hidden_id").val(ids);
            $(".hidden_title").html(' "' + user + '" ');
        });


        $('#deleteGroup').find('#confirm_yes').on('click', function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            //fetching id
            var id = $("#hidden_id").val();

            $.ajax({
                type: "POST",
                url: "{{ route('shareholder.delete_group') }}",
                headers: {
                    'XCSRFToken': $('meta[name="csrf-token"]').attr('content')
                },

                data: "id=" + id,
                success: function (msg) {
                    // console.log(msg);
                    $("#deleteGroup").modal("hide");
                    $("#showMessage").modal("show");
                    // window.location.reload();
                }
            });
        });
        // AJAX DELETE PERMISSION END

        $( "#show_message" ).click(function() {
            window.location.reload();
        });

    </script>



@endsection('scripts')