routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
@require('assets.php');

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/formshareholder', 'ShareHolderController@index')->name('/admin/formshareholder');


Route::group(['prefix' =>ROOT_DIR.'admin', 'middleware' => ['auth'], 'as' => 'admin.'], function () {

    //user register and edit routes
    Route::get('/user', ['uses'=>'UserController@index','as'=>'list_user']);

    Route::get('/user/register',['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit
    Route::get('/user/edit/{id}', ['uses'=>'UserController@editUser','as'=>'edit_user']);
    Route::post('/user/edit', ['uses'=>'UserController@post_editUser','as'=>'update_user']);

    //delete user
    Route::post('/user/delete', ['uses'=>'UserController@deleteUser','as'=>'delete_user']);

    //list user group permission
    Route::get('/permission/group', ['uses'=>'PermissionController@index','as'=>'list_group']);
    Route::get('/permission/group/create', ['uses'=>'PermissionController@showGroupForm','as'=>'register_group']);
    Route::post('/permission/store', ['uses'=>'PermissionController@postGroupForm','as'=>'store_group']);
    Route::get('/permission/view/{id}', ['uses'=>'PermissionController@viewGroup','as'=>'view_group']);

//    Route::get('/permission/group/edit', ['uses'=>'PermissionController@showGroupForm','as'=>'list_group']);


});

//profile routes
Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => ['auth'], 'as' => 'profile.'], function () {

    //user  profile register and edit routes
    Route::get('/{key}',['uses'=>'Usercontroller@getProfile','as'=>'list_profile']);
    Route::post('/edit/profile', ['uses'=>'UserController@editProfile','as'=>'edit']);


});


Route::group(['prefix' =>ROOT_DIR.'shareholder', 'middleware' => ['auth','can:shareholder'], 'as' => 'shareholder.'], function () {

    //share group route
    Route::get('/group', ['uses'=>'ShareHolder\ShareGroupController@index','as'=>'list_group']);
    Route::get('/group/edit/{id}', ['uses'=>'ShareHolder\ShareGroupController@editGroup','as'=>'edit_group']);
    Route::post('/group/add', ['uses'=>'ShareHolder\ShareGroupController@addGroup','as'=>'add_group']);
    Route::post('/group/delete', ['uses'=>'ShareHolder\ShareGroupController@deleteGroup','as'=>'delete_group']);


    //share form
    Route::get('/add_form', ['uses'=>'ShareHolder\ShareHolderController@index','as'=>'add_form']);
    Route::post('/process_form', ['uses'=>'ShareHolder\ShareHolderController@process','as'=>'process_form']);
    Route::get('/list_form', ['uses'=>'ShareHolder\ShareHolderController@list','as'=>'list_form']);
    Route::get('/view/{id}', ['uses'=>'ShareHolder\ShareHolderController@view','as'=>'view']);

    // Edit Form Share and Installment Details

        //Edit Menu
            Route::get('/edit/{id}', ['uses'=>'ShareHolder\ShareHolderController@editMenu','as'=>'edit']);

            Route::get('/edit/form/{id}', ['uses'=>'ShareHolder\ShareHolderController@editForm','as'=>'edit_form']);
            Route::post('/edit/form', ['uses'=>'ShareHolder\ShareHolderController@posteditForm','as'=>'update_form']);

            Route::get('/edit_document/{id}', ['uses'=>'ShareHolder\ShareHolderController@edit_document','as'=>'edit_document']);
            Route::post('/edit_document_form}', ['uses'=>'ShareHolder\ShareHolderController@edit_document_form','as'=>'edit_document_form']);

            Route::get('/edit_installment/{id}', ['uses'=>'ShareHolder\InstallmentController@getInstallmentInformation','as'=>'edit_installment']);
            Route::post('/edit_installment_form/{id}', ['uses'=>'ShareHolder\InstallmentController@editInstallmentInformation','as'=>'edit_installment_form']);


    //end_edit

    //installment
    Route::get('/installment', ['uses'=>'ShareHolder\InstallmentController@index','as'=>'installment']);
    Route::get('/add_installment/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@add_installment','as'=>'add_installment']);
    Route::post('/process_installment', ['uses'=>'ShareHolder\InstallmentController@process_installment','as'=>'process_installment']);

    Route::get('/installment/all/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@view_installment','as'=>'view_installment']);

    Route::get('/installment/detail/{id}', ['uses'=>'ShareHolder\InstallmentController@getSingleInstallment','as'=>'getSingleInstallment']);



    //Notification Routes
    Route::get('/notification', ['uses'=>'ShareHolder\NotificationController@index','as'=>'notification']);
    Route::get('/notiication/message/{id}', ['uses'=>'ShareHolder\NotificationController@showMessageForm','as'=>'notification_message']);
    Route::post('/notiication/message', ['uses'=>'ShareHolder\NotificationController@post_message','as'=>'post_message']);


});


/*Route::group(['prefix' =>ROOT_DIR.'assetsmanagement', 'middleware' => ['auth','can:ams'], 'as' => 'asset.'], function () {*/

    //share group route
    /*Route::get('/add_asset', ['uses'=>'AssetsManagement\ProductController@addAsset','as'=>'add_asset']);*/
    /*Route::post('/add_asset', ['uses'=>'AssetsManagement\ProductController@assetForm','as'=>'add_asset']);
    Route::get('/list_asset', ['uses'=>'AssetsManagement\ProductController@assetList','as'=>'list_asset']);*/
    /*Route::get('/edit_asset/{id}', ['uses'=>'AssetsManagement\ProductController@editAsset','as'=>'edit_asset']);*/
    /*Route::post('/update_asset', ['uses'=>'AssetsManagement\ProductController@updateAsset','as'=>'update_asset']);*/
    /*Route::post('/delete_asset', ['uses'=>'AssetsManagement\ProductController@deleteAsset','as'=>'delete_asset']);*/
    /*Route::get('/view_asset/{id}', ['uses'=>'AssetsManagement\ProductController@viewAsset','as'=>'view_asset']);*/

    /*Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);*/
    /*Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);*/

   /* Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);*/
   


   /* Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);

    Route::get('purchase_form', ['uses'=>'AssetsManagement\ProductController@purchaseForm','as'=>'purchase_form']);
    Route::post('purchase_form', ['uses'=>'AssetsManagement\RequisitionFormController@addPurchaseForm','as'=>'purchase_form']);*/


/*});*/

Route::group(['prefix' =>ROOT_DIR.'storekeeper',  'as' => 'store.'], function () {

    //Storekeeper group route

    //add product directly by the store.
    Route::get('/product/add', ['uses'=>'AssetsManagement\ProductController@addProduct','as'=>'add_product']);
    Route::post('/add_product', ['uses'=>'AssetsManagement\ProductController@productForm','as'=>'store_product']);
    Route::get('/list_product', ['uses'=>'AssetsManagement\ProductController@productList','as'=>'list_product']);
    Route::get('/edit_product/{id}', ['uses'=>'AssetsManagement\ProductController@editProduct','as'=>'edit_product']);
    Route::post('/update_product', ['uses'=>'AssetsManagement\ProductController@updateProduct','as'=>'update_product']);
    Route::post('/delete_product', ['uses'=>'AssetsManagement\ProductController@deleteProduct','as'=>'delete_product']);
    Route::get('/view_product/{id}', ['uses'=>'AssetsManagement\ProductController@viewProduct','as'=>'view_product']);

    //end add product route

    // product add after purchase form
    Route::get('/product/purchase/add/{id}', ['uses'=>'AssetsManagement\ProductController@addProductAfterPurchaseForm','as'=>'add_purchase_product']);
    Route::post('/product/purchase/add', ['uses'=>'AssetsManagement\ProductController@storeProductAfterPurchaseForm','as'=>'store_purchase_product']);

    // end product add after purchase form

    //add vendor
    Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);
    Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);

    Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);
    Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);
    //end vendor route

    //Product Category list and update

app/Product.php
<?php

namespace App;
use App\AssetType;
use App\ProductVendor;
use App\Block;
use App\SubBlock;
use App\AssetName;
use App\SpecificationName;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected  $table= 'products';
    public $timestamps = false;


    public function asset_types(){
    	return $this->belongsTo('App\AssetType','asset_type_id');
    }


    public function product_vendors(){
    	return $this->belongsTo('App\ProductVendor','vendor_id');
    }

    public function product_block(){
    	return $this->belongsTo('App\Block','block_id');
    }

    public function product_sub_block(){
    	return $this->belongsTo('App\SubBlock','sub_block_id');
    }

    public function asset_name(){
        return $this->belongsTo('App\AssetName','asset_name_id');
    }

    public function specification_name(){
        return $this->belongsTo('App\SpecificationName','specification_name_id');
    }

    




    
}

resources/views/assets/store/product/index.blade.php
@extends('layouts.app')
@section('css')
    <link href="{{asset(STATIC_DIR.'assets/global/plugins/select2/select2.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}" rel="stylesheet" type="text/css"/>

    <style>
        .responsive {
            width: 100%;
            max-width: 100px;
            height: auto;
        }
    </style>
@endsection('css')

@section('page_title')
    Product Listing
@endsection

{{--@section('page-title')--}}
        {{--Goods Requisition Files--}}
{{--@endsection('page-title')--}}


@section('content')


    <div class=" portlet light bordered" >
        <div class="row">
            <div class="portlet-body col-md-12 col-sm-12">

                {{--<table class="table table-striped table-bordered table-advance table-hover" id="sample_1">--}}
                <table class="table table-striped table-bordered table-hover" id="group">
                    <thead>
                    <tr>
                        <th>
                            SN
                        </th>
                        <th>
                            Product Name
                        </th>
                        <th>Specification Name</th>

                    

                        <th>
                            Asset Type
                        </th>
                        <th>Quantitiy</th>

                        <th>
                            Vendor
                        </th>

                        <th>Created Date</th>

                        <th>
                            Action
                        </th>


                    </tr>
                    </thead>
                    <tbody >
                    @foreach($list_assets as $element)
                                <tr>
                                    <td>
                                         {{$loop->iteration}}
                                    </td>
                                    <td>
                                         {{$element->asset_name->asset_name}}
                                    </td>
                                    <td>{{$element->specification_name->specification_name}}</td>
                                     <td>
                                         {{$element->asset_types->name}}
                                    </td>
                                    <td>
                                         {{$element->quantity}}
                                    </td>
                                    <td>
                                         {{$element->product_vendors->name}}
                                    </td>
                                    <td>{{$element->created_at}}</td>
                                    <td>
                                        
                                        <a class="btn default btn-xs blue-stripe" href="{{route('store.edit_product',['id'=>$element->id])}}">
                                        <i class="fa fa-pencil"></i> Edit
                                         </a>
                                    
                                    <a class="btn default btn-xs green-stripe" href="{{route('store.view_product',['id'=>$element->id])}}">
                                        <i class="fa fa-eye"></i> View
                                    </a>
                                        
                                        
                                    </td>
                                </tr>
                                @endforeach



                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection('content')
@section('scripts')

    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}" type="text/javascript"></script>

    <script>
        jQuery(document).ready(function() {
            $('#group').DataTable();
        });



    </script>


@endsection('scripts')

resources/views/assets/store/product/view_product.blade.php
@extends('layouts.app')

@section('page_title')
    View Product
@endsection

@section('content')
<!-- BEGIN SAMPLE FORM PORTLET-->
<div class=" portlet light bordered" >
        <div class="row">
            <div class="portlet-body col-md-12 col-sm-12">
                <div class="row">
                        <div class="form-group">
                            <a href="{{route('store.list_product')}}" class="btn btn-sm btn-default ">
                                <i class="fa fa-arrow-circle-left"></i>
                                Back
                            </a>
                        </div>
                </div>
            {{--start 1st row--}}
                <div class="row">
                    <h2>Product Information:</h2>
                    <hr>

                    <h4>Product Category and Its Sub Category</h4>
                    <hr>

                    <div class="col-md-3">
                        <div class="form-group">
                            <strong > Category</strong>
                            <p class="form-control">  {{ucfirst($product->asset_types->name)}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong > Block</strong>
                            <p class="form-control">  {{ucfirst($product->product_block->block_name)}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong > Sub Block</strong>
                            <p class="form-control">  {{ucfirst($product->product_sub_block->sub_block_name)}}</p>
                        </div>
                    </div>

                </div>
            {{--end 1st row--}}

                {{--2nd row--}}
                <div class="row">
                    <div class="col-md-3 ">
                        <div class="form-group">
                            <strong >Product Name:</strong>
                            <p class="form-control">  {{$product->asset_name->asset_name}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Specification</strong>
                            <p class="form-control">  {{$product->specification_name->specification_name}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Unit</strong>
                            <p class="form-control">  {{$product->unit}}</p>
                        </div>
                    </div>

                </div>
            {{--end 2nd row--}}

            {{--start 3rd row--}}
                <div class="row">
                    <hr>
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Quantity</strong>
                            <p class="form-control">  {{$product->quantity}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Per Unit Cost</strong>
                            <p class="form-control">  {{$product->unit_cost}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Amount</strong>
                            <p class="form-control">  {{$product->amount}}</p>
                        </div>
                    </div>
                </div>
            {{--end 3rd row--}}

            {{--start 4th row--}}
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Discount</strong>
                            <p class="form-control">  {{$product->discount}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >VAT</strong>
                            <p class="form-control">  {{$product->vat}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Expected Life</strong>
                            <p class="form-control">  {{$product->expected_life}}</p>
                        </div>
                    </div>
                </div>
            {{--end 4th row--}}

            {{--start 5th row--}}
                <div class="row">
                    <hr>
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Depreciation Method</strong>
                            <p class="form-control">  {{$product->depreciation_method}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Depreciation Value</strong>
                            <p class="form-control">  {{$product->depreciation_value}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Residual Price</strong>
                            <p class="form-control">  {{$product->residual_price}}</p>
                        </div>
                    </div>
            </div>
            {{--end 5th row--}}

            {{--start 6th row--}}
                <div class="row">
                    <hr>
                    @if(isset($product->bill_issue_date))
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Bill Issue Date</strong>
                            <p class="form-control">{{ date('Y-m-d',strtotime($product->bill_issue_date)) }}</p>
                        </div>
                    </div>
                    @endif

                    @if(isset($product->ready_to_use_date))
                    <div class="col-md-3 @if(!empty($product->bill_issue_date))col-md-offset-1  @endif">
                        <div class="form-group">
                            <strong >Ready To Use Date</strong>
                            <p class="form-control">{{ date('Y-m-d',strtotime($product->ready_to_use_date)) }} </p>
                        </div>
                    </div>
                    @endif

                </div>
            {{--end 6th row--}}

            {{--start 7th row--}}
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Product Created Date</strong>
                            <p class="form-control">  {{$product->created_at}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Created Date Nepali</strong>
                            <p class="form-control">  {{$product->nepali_date}}</p>
                        </div>
                    </div>


                </div>
            {{--end 7th row--}}

            {{--start 8th row--}}
             @if(!empty($product->image) && !empty($product->bill))
                <div class="row">
                    <hr>
                    <h4>Uploaded Files</h4>
                    <hr>
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Product Image</strong>
{{--                            <p class="form-control">  {{$product->image}}</p>--}}
                            <img src="{{asset(STATIC_DIR.$product->image)}}" class="img-responsive" alt="">
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Bill Image</strong>
{{--                            <p class="form-control">  {{$product->bill}}</p>--}}
                            <img src="{{asset(STATIC_DIR.$product->image)}}" class="img-responsive" alt="">

                        </div>
                    </div>

                </div>
             @endif
            {{--end 8th row--}}

            {{--start 9th row--}}
                <div class="row">
                    <hr>
                    <h4>Vendor Information:</h4>
                    <hr>
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Vendor Name</strong>
                            <p class="form-control">  {{$product->product_vendors->name}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Email</strong>
                            <p class="form-control">  {{$product->product_vendors->email}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Pan Vat Number</strong>
                            <p class="form-control">  {{$product->product_vendors->pan_vat_number}}</p>
                        </div>
                    </div>
                </div>
            {{--end 9th row--}}

            {{--start 10th row--}}
                <div class="row">
                    <hr>
                    <div class="col-md-3">
                        <div class="form-group">
                            <strong >Vendor Address</strong>
                            <p class="form-control">  {{$product->product_vendors->address}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Vendor Contact</strong>
                            <p class="form-control">  {{$product->product_vendors->contact}}</p>
                        </div>
                    </div>

                    <div class="col-md-3 col-md-offset-1">
                        <div class="form-group">
                            <strong >Mobile Number:</strong>
                            <p class="form-control">  {{$product->product_vendors->mobile_number}}</p>
                        </div>
                    </div>
                </div>
            {{--end 10th row--}}

            </div>


        </div>
</div>


@endsection('content')
@section('scripts')
 
@endsection('scripts')