routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','/public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
@require('assets.php');

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/formshareholder', 'ShareHolderController@index')->name('/admin/formshareholder');


Route::group(['prefix' =>ROOT_DIR.'admin', 'middleware' => ['auth'], 'as' => 'admin.'], function () {

    //user register and edit routes
    Route::get('/user', ['uses'=>'UserController@index','as'=>'list_user']);

    Route::get('/user/register',['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit
    Route::get('/user/edit/{id}', ['uses'=>'UserController@editUser','as'=>'edit_user']);
    Route::post('/user/edit', ['uses'=>'UserController@post_editUser','as'=>'update_user']);

    //delete user
    Route::post('/user/delete', ['uses'=>'UserController@deleteUser','as'=>'delete_user']);

    //list user group permission
    Route::get('/permission/group', ['uses'=>'PermissionController@index','as'=>'list_group']);
    Route::get('/permission/group/create', ['uses'=>'PermissionController@showGroupForm','as'=>'register_group']);
    Route::post('/permission/store', ['uses'=>'PermissionController@postGroupForm','as'=>'store_group']);
    Route::get('/permission/view/{id}', ['uses'=>'PermissionController@viewGroup','as'=>'view_group']);

//    Route::get('/permission/group/edit', ['uses'=>'PermissionController@showGroupForm','as'=>'list_group']);


});

//profile routes
Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => ['auth'], 'as' => 'profile.'], function () {

    //user  profile register and edit routes
    Route::get('/{key}',['uses'=>'Usercontroller@getProfile','as'=>'list_profile']);
    Route::post('/edit/profile', ['uses'=>'UserController@editProfile','as'=>'edit']);


});


Route::group(['prefix' =>ROOT_DIR.'shareholder', 'middleware' => ['auth','can:shareholder'], 'as' => 'shareholder.'], function () {

    //share group route
    Route::get('/group', ['uses'=>'ShareHolder\ShareGroupController@index','as'=>'list_group']);
    Route::get('/group/edit/{id}', ['uses'=>'ShareHolder\ShareGroupController@editGroup','as'=>'edit_group']);
    Route::post('/group/add', ['uses'=>'ShareHolder\ShareGroupController@addGroup','as'=>'add_group']);
    Route::post('/group/delete', ['uses'=>'ShareHolder\ShareGroupController@deleteGroup','as'=>'delete_group']);


    //share form
    Route::get('/add_form', ['uses'=>'ShareHolder\ShareHolderController@index','as'=>'add_form']);
    Route::post('/process_form', ['uses'=>'ShareHolder\ShareHolderController@process','as'=>'process_form']);
    Route::get('/list_form', ['uses'=>'ShareHolder\ShareHolderController@list','as'=>'list_form']);
    Route::get('/view/{id}', ['uses'=>'ShareHolder\ShareHolderController@view','as'=>'view']);

    // Edit Form Share and Installment Details

        //Edit Menu
            Route::get('/edit/{id}', ['uses'=>'ShareHolder\ShareHolderController@editMenu','as'=>'edit']);

            Route::get('/edit/form/{id}', ['uses'=>'ShareHolder\ShareHolderController@editForm','as'=>'edit_form']);
            Route::post('/edit/form', ['uses'=>'ShareHolder\ShareHolderController@posteditForm','as'=>'update_form']);

            Route::get('/edit_document/{id}', ['uses'=>'ShareHolder\ShareHolderController@edit_document','as'=>'edit_document']);
            Route::post('/edit_document_form}', ['uses'=>'ShareHolder\ShareHolderController@edit_document_form','as'=>'edit_document_form']);

            Route::get('/edit_installment/{id}', ['uses'=>'ShareHolder\InstallmentController@getInstallmentInformation','as'=>'edit_installment']);
            Route::post('/edit_installment_form/{id}', ['uses'=>'ShareHolder\InstallmentController@editInstallmentInformation','as'=>'edit_installment_form']);


    //end_edit

    //installment
    Route::get('/installment', ['uses'=>'ShareHolder\InstallmentController@index','as'=>'installment']);
    Route::get('/add_installment/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@add_installment','as'=>'add_installment']);
    Route::post('/process_installment', ['uses'=>'ShareHolder\InstallmentController@process_installment','as'=>'process_installment']);

    Route::get('/installment/all/{unique_id}', ['uses'=>'ShareHolder\InstallmentController@view_installment','as'=>'view_installment']);

    Route::get('/installment/detail/{id}', ['uses'=>'ShareHolder\InstallmentController@getSingleInstallment','as'=>'getSingleInstallment']);



    //Notification Routes
    Route::get('/notification', ['uses'=>'ShareHolder\NotificationController@index','as'=>'notification']);
    Route::get('/notiication/message/{id}', ['uses'=>'ShareHolder\NotificationController@showMessageForm','as'=>'notification_message']);
    Route::post('/notiication/message', ['uses'=>'ShareHolder\NotificationController@post_message','as'=>'post_message']);


});


/*Route::group(['prefix' =>ROOT_DIR.'assetsmanagement', 'middleware' => ['auth','can:ams'], 'as' => 'asset.'], function () {*/

    //share group route
    /*Route::get('/add_asset', ['uses'=>'AssetsManagement\ProductController@addAsset','as'=>'add_asset']);*/
    /*Route::post('/add_asset', ['uses'=>'AssetsManagement\ProductController@assetForm','as'=>'add_asset']);
    Route::get('/list_asset', ['uses'=>'AssetsManagement\ProductController@assetList','as'=>'list_asset']);*/
    /*Route::get('/edit_asset/{id}', ['uses'=>'AssetsManagement\ProductController@editAsset','as'=>'edit_asset']);*/
    /*Route::post('/update_asset', ['uses'=>'AssetsManagement\ProductController@updateAsset','as'=>'update_asset']);*/
    /*Route::post('/delete_asset', ['uses'=>'AssetsManagement\ProductController@deleteAsset','as'=>'delete_asset']);*/
    /*Route::get('/view_asset/{id}', ['uses'=>'AssetsManagement\ProductController@viewAsset','as'=>'view_asset']);*/

    /*Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);*/
    /*Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);*/

   /* Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);*/
   


   /* Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);

    Route::get('purchase_form', ['uses'=>'AssetsManagement\ProductController@purchaseForm','as'=>'purchase_form']);
    Route::post('purchase_form', ['uses'=>'AssetsManagement\RequisitionFormController@addPurchaseForm','as'=>'purchase_form']);*/


/*});*/

Route::group(['prefix' =>ROOT_DIR.'storekeeper',  'as' => 'store.'], function () {

    //Storekeeper group route

    //add product directly by the store.
    Route::get('/product/add', ['uses'=>'AssetsManagement\ProductController@addProduct','as'=>'add_product']);
    Route::post('/add_product', ['uses'=>'AssetsManagement\ProductController@productForm','as'=>'store_product']);
    Route::get('/list_product', ['uses'=>'AssetsManagement\ProductController@productList','as'=>'list_product']);
    Route::get('/edit_product/{id}', ['uses'=>'AssetsManagement\ProductController@editProduct','as'=>'edit_product']);
    Route::post('/update_product', ['uses'=>'AssetsManagement\ProductController@updateProduct','as'=>'update_product']);
    Route::post('/delete_product', ['uses'=>'AssetsManagement\ProductController@deleteProduct','as'=>'delete_product']);
    Route::get('/view_product/{id}', ['uses'=>'AssetsManagement\ProductController@viewProduct','as'=>'view_product']);

    //end add product route

    // product add after purchase form
    Route::get('/product/purchase/add/{id}', ['uses'=>'AssetsManagement\ProductController@addProductAfterPurchaseForm','as'=>'add_purchase_product']);
    Route::post('/product/purchase/add', ['uses'=>'AssetsManagement\ProductController@storeProductAfterPurchaseForm','as'=>'store_purchase_product']);

    // end product add after purchase form

    //add vendor
    Route::get('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorForm','as'=>'add_vendor']);
    Route::post('/add_vendor', ['uses'=>'AssetsManagement\ProductController@vendorAdd','as'=>'add_vendor']);

    Route::get('/view_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@viewVendor','as'=>'view_vendor']);
    Route::get('/edit_vendor/{id}', ['uses'=>'AssetsManagement\ProductController@editVendor','as'=>'edit_vendor']);
    Route::post('/update_vendor', ['uses'=>'AssetsManagement\ProductController@updateVendor','as'=>'update_vendor']);
    Route::post('/delete_vendor', ['uses'=>'AssetsManagement\ProductController@deletVendor','as'=>'delete_vendor']);
    Route::get('/list_vendor', ['uses'=>'AssetsManagement\ProductController@vendorList','as'=>'list_vendor']);
    //end vendor route

    //Product Category list and update

app/Http/Controllers/ShareHolder/NotificationController.php
<?php

namespace App\Http\Controllers\ShareHolder;

use App\FormShare;
use App\Helper\Tools;
use App\InstallmentInformation;
use App\Payment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Mail\NotificationPayment;
use Symfony\Component\Console\Helper\Helper;

class NotificationController extends Controller
{
    public function index()
    {
        $payment_info = FormShare::with('payment_information')->get(['form_status','id','notification','proceeded_for']);
//        dd($payment_info);
//        $data = array();

        //initializing count for badge
        $count = 0;

        foreach ($payment_info as $value){
            $total_installment = $value->payment_information->no_of_installment;
            $temp = $value->proceeded_for . '_expiry_date';

            for($i = 1; $i <= $total_installment; $i ++) {

                if ($value->notification == 1) {

                    if ($value->form_status == $i) {
                        $payment = InstallmentInformation::where('share_form_id', $value->id)->first();
                        //                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->first_expiry_date)));
                        $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->$temp)));

                        if (date('Y-m-d') >= $days_ago) {
                            $count = $count + 1;

                            $data['form'] [] = FormShare::where('id', $value->id)->with('payment_information')->first();

                        }
                    }
                }
            }

//            if($value->notification == 1){
//                $check[] = $count;
//                echo $count;
//
//                if($value->form_status == $count){
//                    $payment = InstallmentInformation::where('share_form_id',$value->id)->first();
////                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->first_expiry_date)));
//                    $temp = $value->proceeded_for.'_expiry_date';
//                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->$temp)));
//
//                    if(date('Y-m-d') >= $days_ago){
//
//                        $data['form'] [] = FormShare::where('id',$value->id)->with('payment_information')->first();
//
//                    }
//                }
//                /*else if($value->form_status == 2){
//
//                    $payment = InstallmentInformation::where('share_form_id',$value->id)->first();
//                    $days_ago = date('Y-m-d', strtotime('-7 days', strtotime($payment->second_expiry_date)));
//
//
//                    if(date('Y-m-d') >= $days_ago){
//                        $data['form'] [] = FormShare::where('id',$value->id)->with('payment_information')->first();
//
//                    }
//                }*/
//            }

        }



        if(!isset($data)){
            $data['token'] = 0;
        }
        else{
            $data['token'] = 1;

        }

        return view('shareholder.Notification.index',$data);

    }

    public function showMessageForm($id){
        $data['installment'] = FormShare::where('id',$id)->with('payment_information')->first();

        $form_status= $data['installment']->form_status;
        $data['installment_detail'] = Tools::getInstallmentDetail($id,$form_status);

        $expiry_date = new \DateTime($data['installment_detail']->expiry_date);
        $current_date = new \DateTime();
        $interval = $expiry_date->diff($current_date);
        if($expiry_date > $current_date){
            $data['remaining_days']= $interval->days + 1;
        }
        else{
            $data['overdue_days']= $interval->days ;

        }
//        dd($data);

        return view('shareholder.Notification.form_message',$data);
    }

    public function post_message(Request $request){
        $this->validate($request,[
            'message' => 'required|min:10',
            'user_email' => 'required|email'
        ]);
        $data = $request->all();

        //call mailable class and send mail.
        \Mail::to($request->user_email)->send(new NotificationPayment($data));

        //after that update form_share table notification columnt to 0
        $id = $request->id;

        $form = FormShare::find($id);

        //updating notification to 0 to not show it again
        $form->notification = 0;
        $form->save();

        \Session::flash('success','Notification Sent Successfully');
        return redirect()->route('shareholder.notification');
    }
}

app/Http/Controllers/ShareHolder/ShareGroupController.php
<?php

namespace App\Http\Controllers\ShareHolder;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ShareGroup;
use App\Helper\Tools;
use Illuminate\Support\Facades\Validator;
use Session;

class ShareGroupController extends Controller
{
    public function index(){

        $data['group'] = ShareGroup::orderBy('id','DESC')->where('slug',1)->get();
        return view('shareholder.ShareGroup.list_group',$data);
    }

    public function editGroup($id){
        $data['group'] = ShareGroup::find($id);

        if(empty($data['group'])) {
            abort(404);
        }

        return view('shareholder.ShareGroup.edit_group',$data);
    }

    public function addGroup(Request $request){

        $this->validate($request,[
            'group_name' => 'required',
            'action' => 'required'
        ]);
//        dd($request->all());

        //slug 1 = group
        //slug 2 = individual

        if($request->action == 'add'){
            $group = new ShareGroup();
            $group->slug = 1;
            $group->created_at = date('Y-m-d h:i:s');
            $group->created_by = \Auth::user()->id;
        }
        else
        {
            $group =  ShareGroup::find($request->id);
        }


        $group->name = $request->group_name;

        $group->save();

        if($request->action == 'add'){
            \Session::flash('success','Group Created Successfully');
            return redirect()->back();

        }
        else{
            \Session::flash('success','Group Updated Successfully');
            return redirect()->route('shareholder.list_group');

        }
    }

    public function deleteGroup(Request $request){
        $validator = Validator::make($request->all(), [
            'id' => 'required',
        ]);

        if ($validator->fails()) {
            \Session::flash('error','Error in Deleting Group');
            $responseData = Tools::setResponse('fail', 'Missing Parameter', '', '');
            $status = 422;

            return response()->json($responseData,$status);
        }

        $data = ShareGroup::find($request->id);
        $data->delete();

        \Session::flash('success','Group Deleted Successfully');
        return redirect()->back();
    }
}

resources/views/shareholder/Installment/index.blade.php
@extends('layouts.app')
@section('css')

<link href="{{asset(STATIC_DIR.'assets/global/plugins/select2/select2.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}" rel="stylesheet" type="text/css"/>

@endsection('css')

@section('page_title')
    Installment
@endsection('page-title')

@section('page-title')
    Search Installment Payee
@endsection('page-title')


@section('content')

<!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet box blue-madison">
                        <div class="portlet-title">
                            <div class="caption">
                                Search and Add Installment
                            </div>
                            
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <form action="{{route('shareholder.installment')}}" method="GET">
                                    @csrf
                                    <div class="form-group">

                                        <div class="col-md-4">
                                            <select  class="form-control" id="share_group_type" name="search_type"  required>
                                                <option value="" hidden >Select Search Type</option>
                                                <option value="individual">Individual</option>
                                                <option value="group">Group</option>
                                            </select>

                                        </div>

                                        <button type="submit" class="btn red"> <i class="fa fa-search-minus"></i> Search</button>


                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="portlet-body">
                            @if($token == 'all')
                                <h3>All Listing</h3>
                            @elseif($token == 'group')
                                <h3>Searching through Group</h3>
                            @else
                                <h3>Searching through Individual</h3>
                            @endif
                                <table class="table table-striped table-bordered table-hover" id="group">
                            <thead>
                            <tr>
                                <th>
                                    S.N.
                                </th>

                                <th>
                                     Shareholder Name
                                </th>
                                <th>
                                     Unique ID
                                </th>
                                <th>
                                     Total Installment:
                                </th>

                                <th>
                                     Remaining Installment
                                </th>

                                <th>Action</th>
                               
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($form_share as $value)
                                <tr>
                                    <td>
                                        {{$loop->iteration}}
                                    </td>

                                    <td>
                                        {{$value->shareholder_name}}
                                    </td>

                                    <td>
                                        {{$value->unique_id}}
                                    </td>

                                    <td>
                                        {{$value->payment_information->no_of_installment}}
                                    </td>
                                    <td>
                                        {{$value->payment_information->remaining_installment}}
                                    </td>

                                    <td>
                                        @if($value->payment_information->remaining_installment != 0)
                                            <a href="{{route('shareholder.add_installment',$value->id)}}" class="btn btn-sm  btn-success">
                                                {{--<i class="fa fa-plus-circle"></i> Add</a>--}}
                                            <i class="icon-plus"></i> Add</a>

                                        @endif
                                            <a href="{{ route('shareholder.view_installment',$value->id) }}" class="btn btn-sm btn-primary">
                                                <i class="fa fa-eye"></i> View
                                            </a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->

@endsection('content')
@section('scripts')
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}" type="text/javascript"></script>

    <script>
        jQuery(document).ready(function() {
            $('#group').DataTable();
        });
    </script>

@endsection('scripts')

resources/views/shareholder/Installment/view_installment.blade.php
@extends('layouts.app')

@section('css')

    <style>
        .responsive {
            width: 100%;
            max-width: 100px;
            height: auto;
        }
    </style>
@endsection('css')

@section('page_title')
    Statement
@endsection

@section('page-title')
     Installment Report
@endsection('page-title')


@section('content')

    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div style="margin-bottom:50px;">
          <a href="{{route('shareholder.installment')}}" class="btn btn-sm btn-success pull-left"><i class="m-icon-swapleft m-icon-white"></i> Back</a>

    </div>
    
    <div class="portlet box blue-madison">
        <div class="portlet-title">
            <div class="caption">
                  Installment Information
            </div>

        </div>
        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                    <th>
                        Shareholder Name
                    </th>
                    <th>
                        Form ID
                    </th>
                    <th>
                        Group Type
                    </th>
{{--                    @if($info->group_type == 'group')--}}
                    <th>
                        Group Name
                    </th>
                    {{--@endif--}}
                    <th>
                        Committed Amount
                    </th>

                    <th>
                        Total Paid Amount
                    </th>
                    <th>
                        Total Remaining
                    </th>
                    <th>
                        Total Installment
                    </th>
                    <th>
                       Remaining Installment
                    </th>



                </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>
                                {{$info->shareholder_name}}
                            </td>
                            <td>
                                {{$info->unique_id}}
                            </td>
                            <td>
                                {{$info->group_type}}
                            </td>

                            {{--@if($info->group_type == 'group')--}}
                                <td>
                                    {{$group_name->name}}
                                </td>
                            {{--@endif--}}
                            <td>
                                Rs {{$info->payment_information->committed_amount}}
                            </td>
                            <td>
                                Rs {{$info->payment_information->total_paid_amount}}
                            </td>
                            <td>
                                Rs {{$info->payment_information->committed_amount - $info->payment_information->total_paid_amount}}
                            </td>

                            <td>
                                {{$info->payment_information->no_of_installment}}
                            </td>

                            <td>
                                {{$info->payment_information->remaining_installment}}
                            </td>

                        </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="portlet box blue-madison">
        <div class="portlet-title">
            <div class="caption">
                All Paid Installment Information
            </div>

        </div>
        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" >
                <thead>
                <tr>
                    <th>
                        S.N.
                    </th>

                    <th>
                        Installment
                    </th>
                    <th>
                        Payment Date
                    </th>

                    <th>
                        Paid Amount
                    </th>

                    <th>
                        Due Amount
                    </th>

                    <th>
                        Advance Amount
                    </th>


                    <th>Status</th>
                    <th>Action</th>


                </tr>
                </thead>
                <tbody>
                @foreach($payments as $value)
                    <tr>
                        <td>
                            {{$loop->iteration}}
                        </td>

                        <td>
                            {{ucfirst($value->installment_name)}} Installment
                        </td>
                        <td>
                            {{$value->installment_nep_date}}
                        </td>
                        <td>
                            {{$value->installment_paid_amount}}
                        </td>

                        <td>
                            {{$value->less_payment}}
                        </td>

                        <td>
                            {{$value->advance_payment}}
                        </td>

                        <td>
                            paid
                        </td>
                        <td>
                            <a href="{{route('shareholder.getSingleInstallment',$value->id)}}" class="btn btn-sm green">View Details</a>

                        </td>
                    </tr>
                @endforeach


                </tbody>
            </table>
        </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->

@endsection('content')
@section('scripts')

   {{-- <script src="{{asset(STATIC_DIR.'assets/admin/pages/scripts/table-advanced.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/select2/select2.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js')}}" type="text/javascript"></script>
    <script src="{{asset(STATIC_DIR.'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}" type="text/javascript"></script>

    <script>
        jQuery(document).ready(function() {

            Demo.init(); // init demo features
            TableAdvanced.init();
        });
    </script>--}}

@endsection('scripts')